{
 "title": "API网关",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "API名称", "query": "apigateway" },
   { "name": "id", "query": "apigateway($name)" }
  ]
 },
 "panels": [
  {
   "title": "code2XX(个)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "返回码2xx个数",
     "dimensions": [ "$id" ],
     "metric": "code2XX",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "code4XX(个)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "返回码4xx个数",
     "dimensions": [ "$id" ],
     "metric": "code4XX",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "code5XX(个)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "返回码5xx个数",
     "dimensions": [ "$id" ],
     "metric": "code5XX",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "流入带宽(KBytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "流入流量",
     "dimensions": [ "$id" ],
     "metric": "TrafficRX",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "流出带宽(KBytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "流出流量",
     "dimensions": [ "$id" ],
     "metric": "TrafficTX",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "响应时间(ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "响应时间",
     "dimensions": [ "$id" ],
     "metric": "Latency",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "总体请求次数(个)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "总体请求次数",
     "dimensions": [ "$id" ],
     "metric": "SumQPS",
     "period": "60",
     "project": "acs_apigateway_dashboard",
     "target": [ "Count" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Count" ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  }
 ]
}