{
 "title": "Elasticsearch",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "集群名称",
    "query": "dimension(acs_elasticsearch,ClusterIndexQPS,null,null)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "dimension(acs_elasticsearch,NodeCPUUtilization,null,null)"
   },
   {
    "name": "es_id",
    "label": "es_id",
    "query": "dimension(acs_elasticsearch,NodeCPUUtilization,null,null)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群状态(value)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "集群状态",
     "dimensions": [ "$es_id" ],
     "metric": "ClusterStatus",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "快照状态(value)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "快照状态",
     "dimensions": [ "$es_id" ],
     "metric": "ClusterAutoSnapshotLatestStatus",
     "period": "60",
     "project": "acs_elasticsearch",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "集群写入QPS(Count/Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "集群写入QPS",
     "dimensions": [ "$es_id" ],
     "metric": "ClusterIndexQPS",
     "period": "60",
     "project": "acs_elasticsearch",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "集群查询QPS(Count/Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "集群查询QPS",
     "dimensions": [ "$es_id" ],
     "metric": "ClusterQueryQPS",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "节点CPU使用率(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "节点CPU使用率",
     "dimensions": [ "$es_id" ],
     "metric": "NodeCPUUtilization",
     "project": "acs_elasticsearch",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "节点磁盘使用率(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "节点磁盘使用率",
     "dimensions": [ "$es_id" ],
     "metric": "NodeDiskUtilization",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "节点HeapMemory使用率(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "节点HeapMemory使用率",
     "dimensions": [ "$es_id" ],
     "metric": "NodeHeapMemoryUtilization",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "节点load_1m(value)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "节点load_1m",
     "dimensions": [ "$es_id" ],
     "metric": "NodeLoad_1m",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "Exception次数(个)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "Exception次数",
     "dimensions": [ "$es_id" ],
     "metric": "NodeStatsExceptionLogCount",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "FullGc次数(个)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "FullGc次数",
     "dimensions": [ "$es_id" ],
     "metric": "NodeStatsFullGcCollectionCount",
     "project": "acs_elasticsearch",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "NodeStatsNetworkinPackages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "NodeStatsNetworkinPackages",
     "dimensions": [ "$es_id" ],
     "metric": "NodeStatsNetworkoutPackages",
     "period": "60",
     "project": "acs_elasticsearch",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "节点网络流出包(个)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "节点网络流出包",
     "dimensions": [ "$es_id" ],
     "metric": "NodeStatsNetworkoutPackages",
     "project": "acs_elasticsearch",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  }
 ]
}