{
 "title": "日志服务",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project_name", "label": "项目名", "query": "project_name" },
   {
    "name": "logstore_name",
    "label": "logstore",
    "query": "project_logstore($project_name)"
   },
   {
    "name": "id",
    "query": "logservice($project_name,$logstore_name)"
   }
  ]
 },
 "panels": [
  { "title": "基础", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "写入流量(bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "流入流量",
     "dimensions": [ "$id" ],
     "metric": "LogInflow",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "原始数据大小(bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "原始数据大小",
     "dimensions": [ "$id" ],
     "metric": "NetFlow",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "总体QPS(个)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "总体QPS",
     "dimensions": [ "$id" ],
     "metric": "SumQPS",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Count" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Count" ]
    }
   ]
  },
  {
   "title": "操作次数(个)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "操作次数",
     "dimensions": [ "$id" ],
     "metric": "LogMethodQPS",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Count" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Count" ]
    }
   ]
  },
  {
   "title": "服务状态(个)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "服务状态",
     "dimensions": [ "$id" ],
     "metric": "LogCodeQPS",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Count" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Count" ]
    }
   ]
  },
  {
   "title": "写入行数(Lines/Minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "写入行数",
     "dimensions": [ "$id" ],
     "metric": "InflowLine",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "读取流量(bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "读取流量",
     "dimensions": [ "$id" ],
     "metric": "LogOutflow",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  { "title": "客户端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "客户端解析成功流量(bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "客户端解析成功流量",
     "dimensions": [ "$id" ],
     "metric": "SuccessdByte",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "客户端解析成功行数(Lines)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "客户端解析成功行数",
     "dimensions": [ "$id" ],
     "metric": "SuccessdLines",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "客户端解析失败行数(Lines)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "客户端解析失败行数",
     "dimensions": [ "$id" ],
     "metric": "FailedLines",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "客户端错误次数(次)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "客户端错误次数",
     "dimensions": [ "$id" ],
     "metric": "AlarmPV",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Sum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Sum" ]
    }
   ]
  },
  {
   "title": "客户端错误机器数(次)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "客户端错误机器数",
     "dimensions": [ "$id" ],
     "metric": "AlarmUV",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Count" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Count" ]
    }
   ]
  },
  {
   "title": "发生错误IP统计(次)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "发生错误IP统计",
     "dimensions": [ "$id" ],
     "metric": "AlarmIPCount",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Count" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Count" ]
    }
   ]
  },
  {
   "title": "消费落后时长(Second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "describe": "消费落后时长",
     "dimensions": [ "$id" ],
     "metric": "ConsumerGroupFallBehind",
     "period": "60",
     "project": "acs_sls_dashboard",
     "target": [ "Maximum" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Maximum" ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 74 },
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  }
 ]
}