{
 "title": "Redis集群版",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "redis_name",
    "label": "redis实例",
    "query": "dimension(acs_kvstore,ShardingCpuUsage,null,null)"
   },
   {
    "name": "redis_node",
    "label": "redis节点",
    "query": "dimension(acs_kvstore,ShardingCpuUsage,null,null)"
   },
   {
    "name": "redis_id",
    "label": "redis",
    "query": "dimension(acs_kvstore,ShardingCpuUsage,null,null)"
   }
  ]
 },
 "panels": [
  { "title": "基础监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU 使用率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingCpuUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingMemoryUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "连接数使用率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingConnectionUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "流入带宽使用率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingIntranetInRatio",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "流出带宽使用率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingIntranetOutRatio",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  { "title": "延时监控项", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "数据节点 平均响应时间(us)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingAvgRt",
     "period": "60",
     "project": "acs_kvstore",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 最大响应时间(us)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingMaxRt",
     "period": "60",
     "project": "acs_kvstore",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  { "title": "其它", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "数据节点 流出带宽(KByte/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingIntranetOut",
     "project": "acs_kvstore",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 流入带宽(KByte/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingIntranetIn",
     "project": "acs_kvstore",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 内存使用量(bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingUsedMemory",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 命中率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingHitRate",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 平均每秒访问次数(个)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingUsedQPS",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 QPS使用率(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingQPSUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 已用连接数(个)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingUsedConnection",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据节点 缓存内 Key 数量(个)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$redis_id" ],
     "metric": "ShardingKeys",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 75 },
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  }
 ]
}